# Generated by Django 4.2.4 on 2024-03-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='slugify',
        ),
    ]
