# Generated by Django 4.2.4 on 2024-03-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[("Ko'chmas mulk", "Ko'chmas mulk"), ('Transport', 'Transport'), ('Elektrotexnika', 'Elektrotexnika'), ("Ish o'rni", "Ish o'rni")], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
